{{- if .Values.pql.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pql.storage.pvcName | quote }}
spec:
  accessModes:
{{- range .Values.pql.storage.accessModes }}
    - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.pql.storage.size | quote }}
  storageClassName: {{ .Values.pql.storage.storageClassName | quote }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pql.storage.pvName | quote }}
spec:
  capacity:
    storage: {{ .Values.pql.storage.size | quote }}
  accessModes:
{{- range .Values.pql.storage.accessModes }}
    - {{ . | quote }}
{{- end }}
  hostPath:
    path: {{ .Values.pql.storage.hostPath | quote }}
    type: DirectoryOrCreate
  storageClassName: {{ .Values.pql.storage.storageClassName | quote }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ .Values.pql.storage.pvcName | quote }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}

