{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "autoptic-ui.fullname" . }}-external-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "autoptic-ui.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ include "autoptic-ui.fullname" . }}-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
  - secretKey: webui-secret-key
    remoteRef:
      key: {{ .Values.externalSecrets.webuiSecretKeyPath }}
  - secretKey: openai-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.openaiApiKeyPath }}
  {{- if .Values.externalSecrets.grokApiKeyPath }}
  - secretKey: grok-api-key
    remoteRef:
      key: {{ .Values.externalSecrets.grokApiKeyPath }}
  {{- end }}
  {{- if .Values.externalSecrets.googleClientSecretPath }}
  - secretKey: google-client-secret
    remoteRef:
      key: {{ .Values.externalSecrets.googleClientSecretPath }}
  {{- end }}
  {{- if .Values.externalSecrets.oktaClientSecretPath }}
  - secretKey: okta-client-secret
    remoteRef:
      key: {{ .Values.externalSecrets.oktaClientSecretPath }}
  {{- end }}
{{- end }}
