{{- if and .Values.ui.enabled (not .Values.externalSecrets.enabled) (not .Values.hooks.masterKey.generate) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autoptic-ui.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "autoptic-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  webui-secret-key: {{ .Values.ui.secrets.webuiSecretKey | required "ui.secrets.webuiSecretKey is required" }}
  openai-api-key: {{ .Values.ui.secrets.openaiApiKey | required "ui.secrets.openaiApiKey is required" }}
  {{- if .Values.ui.secrets.grokApiKey }}
  grok-api-key: {{ .Values.ui.secrets.grokApiKey }}
  {{- end }}
  {{- if .Values.ui.secrets.googleClientSecret }}
  google-client-secret: {{ .Values.ui.secrets.googleClientSecret }}
  {{- end }}
  {{- if .Values.ui.secrets.oktaClientSecret }}
  okta-client-secret: {{ .Values.ui.secrets.oktaClientSecret }}
  {{- end }}
{{- end }}
