{{- if .Values.serviceAccounts.s3DynamoDbAccess.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autoptic-server.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "autoptic-server.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation
    {{- with .Values.serviceAccounts.s3DynamoDbAccess.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccounts.s3DynamoDbAccess.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccounts.s3DynamoDbAccess.roleArn | quote }}
    {{- end }}
{{- end }}
